### ISSUE TITLE
Only returns 5 games

### ISSUE THREAD

**Issue by johtso** [SafwanSipai/geo-insight#1]
Hey, was excited to try this out, but it only seems to be showing 5 games played. Any ideas?

**Comment by SafwanSipai** [comment]
Does it only show 5 games for all the modes? Or just one particular mode?

**Comment by johtso** [comment]
2 moving, 3 no moving. Slider maxes out at 5.

**Comment by johtso** [comment]
Oh wait, I see what's going on, it ignores all games that aren't "Standard" mode, and I only play duels. Is there a reason you can't show data for duels games?

**Comment by SafwanSipai** [comment]
> Oh wait, I see what's going on, it ignores all games that aren't "Standard" mode, and I only play duels. Is there a reason you can't show data for duels games?

I am actually working on adding duels. But before that I am also changing the frontend from Streamlit to React, so adding duels is not the topmost priority right now :)

**Comment by johtso** [comment]
Awesome! Good luck, look forward to checking it out
